name: Toggle README Image

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  toggle-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Toggle image in README
        run: |
          FILE="README.md"
          OLD="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.wallpapersafari.com%2F76%2F95%2FDT28IP.gif&f=1&nofb=1&ipt=a97ddd8f051f340dbb9cb4697beb64f022cec5dd68513590d629ff15a8a25832"
          NEW="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.tenor.com%2F6sMr16etjisAAAAC%2Fnature-scenery.gif&f=1&nofb=1&ipt=dce1111971ce949613daf9f091c0948e7d62ec7429fc7b0ffece8b724f5b6d68"

          # Check if the old image is in the README and replace it with the new one
          if grep -q "$OLD" "$FILE"; then
            # Replace old image with the new one
            sed -i "s|!\[dynamic-ad\]($OLD)|![dynamic-ad]($NEW)|" "$FILE"
          else
            # If the old image is not found, then the new one should be replaced with the old one
            sed -i "s|!\[dynamic-ad\]($NEW)|![dynamic-ad]($OLD)|" "$FILE"
          fi

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "ci: toggle dynamic image"
          git push
